title: Arthur Berberyan
logo: /assets/img/IMG_7391.jpg
description: <em> I laugh when I hear that the fish in the water is thirsty. </em> -Kabir 
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-minimal
